### ISSUE TITLE
Centralized vs decentralized

### ISSUE THREAD

**Issue by fitzyjoe** [TeslaGov/clarakm-aws-events#2]
This project has a centralized approach to messages, with all of the topics and queues defined in a central location.  This doesn't seem right - shouldn't each service define the topics and queues?

**Comment by crain9412** [comment]
We define topics and subjects in this library because they have to be reused across microservices.  Both producer and consumer attempt to create a topic and utilize the subjects, so it's important that they are consistent across the system.  Each consumer is responsible for its own queues, because they are not shared with any other microservice.

**Comment by crain9412** [comment]
To clarify, the code works like this right now:

Producer:
1. Create topic if it doesn't exist
2. Publish events to topic with a subject

Consumer:
1. Create queue if it doesn't exist
2. Create topic if it doesn't exist
3. Subscribe queue to topic
4. Listen for additions to the queue and handle them based on subject

Basically, the name of the topic, the subject, and the content of the message are the contracts in our system that are shared among Microservices.  Changes any of these can be breaking changes, so I think it's best we provide topics and subjects in this library. 

 I don't think we should have shared DTOs in this library because we can build our consumers to be less brittle if they only pull the fields they need out of the message, however you could make an argument that they should be in this library as well.

**Comment by kevinmichaelchen** [comment]
> We define topics and subjects in this library because they have to be reused across microservices.

That's pretty much the primary justification for this library (besides providing helper functions to create topics, queues, and subscriptions).

**Comment by fitzyjoe** [comment]
This isn't working in my brain at all.  In this model each micro service
uses this API to create the topics, queues, and subscriptions... so long as
they are enumerated in this centralized place.  It makes more sense to me
that each service that is publishing would create its own topics and each
service that is listening would create its own queues and subscriptions.  I
know they have to get the names consistent for this whole thing to work.
This centralization is as bad as just making this API create *all* of the
topics, queues, and subscriptions the first time it is called.

**Comment by crain9412** [comment]
"It makes more sense to me
that each service that is publishing would create its own topics and each
service that is listening would create its own queues and subscriptions."

That's how it works, this library is just to facilitate that. 

Consumers must also attempt to create topics just in case they come up first.  The way we've engineered this, it doesn't matter if Consumers or Producers come online first, each creates the resources they need to function.  Producers create topics, and Consumers create queues, topics, and subscriptions.  

You could distribute these contracts throughout the microservices which is what I was originally doing, however it just leads to duplicated Enums/static Strings in each service.

**Comment by crain9412** [comment]
The library is versioned, so if you need to add a new topic, you simply add

**Comment by kevinmichaelchen** [comment]
This library is merely a solution for “how do I reduce boilerplate in my spring boot app?” and “how can I guarantee there are no typos in my topic names to ensure no rogue topics get created.”
